services:
    klehm_sylius_brevo.sender_adapter:
        class: Klehm\SyliusBrevoPlugin\Mailer\Adapter\BrevoAdapter
        arguments:
            $brevoMailer: '@Klehm\SyliusBrevoPlugin\Mailer\BrevoMailerInterface'

    Klehm\SyliusBrevoPlugin\Provider\TemplateIdProvider:
        arguments:
            $templates: '%klehm_sylius_brevo.templates%'
    Klehm\SyliusBrevoPlugin\Provider\TemplateIdProviderInterface: '@Klehm\SyliusBrevoPlugin\Provider\TemplateIdProvider'

    Klehm\SyliusBrevoPlugin\Mailer\BrevoMailer:
        arguments:
            $templateIdProvider: '@Klehm\SyliusBrevoPlugin\Provider\TemplateIdProviderInterface'
            $brevoApiClient: '@Klehm\SyliusBrevoPlugin\Api\BrevoApiClientInterface'
            $dispatcher: "@event_dispatcher"
            $locale: '@sylius.context.locale'

    Klehm\SyliusBrevoPlugin\Mailer\BrevoMailerInterface: '@Klehm\SyliusBrevoPlugin\Mailer\BrevoMailer'

    Klehm\SyliusBrevoPlugin\Api\Builder\HtmlMessagePayloadBuilder: ~
    Klehm\SyliusBrevoPlugin\Api\Builder\HtmlMessagePayloadBuilderInterface: '@Klehm\SyliusBrevoPlugin\Api\Builder\HtmlMessagePayloadBuilder'
    
    Klehm\SyliusBrevoPlugin\Api\Builder\TemplateMessagePayloadBuilder: ~
    Klehm\SyliusBrevoPlugin\Api\Builder\TemplateMessagePayloadBuilderInterface: '@Klehm\SyliusBrevoPlugin\Api\Builder\TemplateMessagePayloadBuilder'

    Klehm\SyliusBrevoPlugin\Api\BrevoApiClient:
        arguments:
            $apiKey: "%klehm_sylius_brevo.api_key%"
            $templateMessagePayloadBuilder: '@Klehm\SyliusBrevoPlugin\Api\Builder\TemplateMessagePayloadBuilderInterface'
            $htmlMessagePayloadBuilder: '@Klehm\SyliusBrevoPlugin\Api\Builder\HtmlMessagePayloadBuilderInterface'

    Klehm\SyliusBrevoPlugin\Api\BrevoApiClientInterface: '@Klehm\SyliusBrevoPlugin\Api\BrevoApiClient'

    Klehm\SyliusBrevoPlugin\Cli\ListBrevoTransactionalTemplatesCommand:
        arguments:
            $brevoApiClient: '@Klehm\SyliusBrevoPlugin\Api\BrevoApiClientInterface'
        tags:
            - { name: "console.command" }

    Klehm\SyliusBrevoPlugin\EventListener\BrevoMailerDataListener:
        arguments: []
        tags:
            - { name: 'kernel.event_listener', event: 'klehm_sylius_brevo_plugin.mailer_data', method: 'onMailerData' }
